### PR TITLE
Make Types java.io.Serializable

### PR DESCRIPTION
**Pull request by ydanneg**
fixes https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt/issues/137

### CODE REVIEW

**Comment by ydanneg** [comment]
There is a problem:
https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-presentation-exchange-kt/issues/137#issuecomment-2015018285

**Review by babisRoutis — CHANGES_REQUESTED** [review]
- [x] Please add a unit test like the one proposed, testing more complex presentation definition cases.
- [x] Please mark also the `PresentationSubmission` classes also as `java.io.serializable`

**Comment by babisRoutis** [comment]
@ydanneg thanks.

Now it's reproducible. Need to sort out the `Filter = JsonObject` problem, I guess :thinking:

**Comment by ydanneg** [comment]
Hackish but works :)
https://github.com/ydanneg/eudi-lib-jvm-presentation-exchange-kt/compare/feat/serializable...ydanneg:eudi-lib-jvm-presentation-exchange-kt:feat/serializable-hack?expand=1

**Comment by babisRoutis** [comment]
@ydanneg 

I think we have found an alternative solution on this. In a nutshell involves changing the Filter from being an alias of `JsonObject`
to be a value class which contains a json as string and a custom JsonSerializer.

I am not sure how we should proceed this PR. I see the following options:
1. Stop this PR and let us redefine the `Fitler` add the test and the `java.io.Serializable` 
2. We can apply to main the redefinition of `Filter` and then you can rebase your branch from main.

What do you think?

**Comment by ydanneg** [comment]
I can rebase later, sure.

**Comment by babisRoutis** [comment]
@ydanneg I see that I can write to your branch. Is it ok with you to apply the changes on your branch ?

(On Monday :smile: )

**Comment by ydanneg** [comment]
> @ydanneg I see that I can write to your branch. Is it ok with you to apply the changes on your branch ?
> 
> (On Monday :smile: )
> 
> 

sure. go ahead! :)

**Review by babisRoutis — APPROVED** [review]

**Comment by babisRoutis** [comment]
@vafeini Can you please review this PR? 
If you agree we can proceed and perhaps release a fix version.

**Review by ydanneg — COMMENTED** [review]
lgtm

**Review by babisRoutis — APPROVED** [review]

**Review by vafeini — APPROVED** [review]

**Pull request merged**
